config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :videos
  root 'pages#home'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/subtitle.rb
# frozen_string_literal: true

class Subtitle < ApplicationRecord
  belongs_to :video

  has_one_attached :upload_file
end

app/models/video.rb
# frozen_string_literal: true

class Video < ApplicationRecord
  has_one :subtitle
  accepts_nested_attributes_for :subtitle, allow_destroy: true

  delegate :upload_file, to: :subtitle, prefix: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  def home
    @video = Video.new
  end
end

app/controllers/videos_controller.rb
# frozen_string_literal: true

class VideosController < ApplicationController
  before_action :set_video, only: %i[show edit update destroy]

  def index
    @videos = Video.all
  end

  def show; end

  def new
    @video = Video.new
  end

  def edit; end

  def create
    @video = Video.new(video_params)

    respond_to do |format|
      if @video.save
        format.html { redirect_to root_path, notice: 'Video was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @video.destroy
  end

  private

  def set_video
    @video = Video.find(params[:id])
  end

  def video_params
    params.require(:video).permit(:title, :url, :stoptime,
                                  subtitle_attributes: %i[id upload_file])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/form_helper.rb
# frozen_string_literal: true

module FormHelper
  def setup_video(video)
    video.subtitle ||= Subtitle.new if video
    video
  end
end

app/helpers/pages_helper.rb
# frozen_string_literal: true

module PagesHelper
end

app/helpers/videos_helper.rb
# frozen_string_literal: true

module VideosHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title MovieApp
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'vue_app'

  %body
    #vue-content.container.grid
      = render partial: "share/header"
      %main.main.grid
        = yield
      = render partial: "share/sidebar"
      = render partial: "share/footer"

app/views/pages/home.html.haml
= render partial: "share/video_player"

app/views/share/_footer.html.haml
%footer.footer.grid
  %h4
    ="&copy; Copyright #{Date.current.year}, YK".html_safe

app/views/share/_header.html.haml
%header.header
  %nav#headerNav.overlay
    %a.closebtn{href: 'javascript:void(0)', "@click":'closeNav'} &times;

    .overlay-content
      = link_to 'Login', '#'
      = link_to 'History', "#"
      = link_to 'All Videos', "#", {remote: true, "@click":"openModal('modalAllVideos')"}
      = link_to 'Add Video', '#', {remote: true, "@click":"openModal('modalForm')"}
  %span{'@click':'openNav'}=  image_tag('logo.png', size:'70x70')
= render partial: 'share/modal'

app/views/share/_modal.html.haml
#modalForm.modal
  .modal-content
    %span.close{"@click": "closeModal('modalForm')", title: "Close Modal"} ×
    = form_with(model: setup_video(@video), local: true, class: "modal-content animate") do |form|
      .container
        .field
          %b= form.label :title
          = form.text_field :title, placeholder: "Enter Title"
        .field
          %b= form.label :url
          = form.text_field :url, placeholder: "Enter Video Url"
        = form.fields_for :subtitle do |f|
          .field
            = f.label :upload_file
            = f.file_field :upload_file

        %button{:type => "submit"} Add Video
#modalAllVideos.modal
  .modal-content
    %span.close{"@click": "closeModal('modalAllVideos')", title: "Close Modal"} ×
    .container
      %h3 All videos
      = render 'videos/videos'

app/views/share/_sidebar.html.haml
%aside.sidebar.grid
  .sidepanel#sidePanel
    %a.closebtn{:href => "javascript:void(0)", "@click": "closeSidebar"} &times;
    %h2 Your last videos
    %ul
      %li.sidebar-item{"v-for": "(video, index) in videos_list"}
        %p{"@click":"changeVideofromSidebar(video.url)"} {{video.title}}
        %span
          %button{"@click": "removeVideo(index)"} &times;
  %button.openbtn{"@click": "openSidebar"} &#9776;

app/views/share/_video_player.html.haml
.video_player_box
  %video#videoElement{"controls":"",
      "@canplay":"updatePaused", "@playing":"updatePaused", "@pause":"updatePaused",
      ":src": "url"}
    %p Sorry, there's a problem playing this video. Please try using a different browser.

  .video_player__form
    %input.form__url_title{"v-model": "url_title", type: "text", placeholder: "Video url title"}
    %input.form__url{"v-model": "url", type: "text", placeholder: "Video url"}
    %input.form__subtitle{"@change": "loadSubtitle($event)", type: "file", placeholder: "Video subtitle"}
    %input.form_submit{"@click":"addVideo", type: "submit", value: "Add video to sidebar"}

app/views/videos/_form.html.haml
= form_with(model: setup_video(video), local: true) do |form|
  - if video.errors.any?
    #error_explanation
      %h2
        = pluralize(video.errors.count, "error")
        prohibited this video from being saved:
      %ul
        - video.errors.full_messages.each do |message|
          %li= message
  .field
    = form.label :title
    = form.text_field :title
  .field
    = form.label :url
    = form.text_field :url
  = form.fields_for :subtitle do |f|
    .field
      = f.label :upload_file
      = f.file_field :upload_file

  .actions
    = form.submit

app/views/videos/_videos.html.haml
%div{'v-for': '(video, index) in videos'}
  .container{'v-bind:id': "'videoId-'+ video.id" }
    %p{ "@click": 'changeVideofromModal(video.url)' } {{ video.title }}
    %p {{ video.url }}
    %p {{ video.stoptime }}
    %p
      <a :href="'videos/' + video.id + '/edit'" class='btn btn-default'>  Edit </a>
      %span{'@click':"deleteVideo(video.id)", class: 'btn btn-danger'} Destroy
  %hr

app/views/videos/edit.html.haml
%h1 Editing Video
= render 'form', video: @video
= link_to 'Show', @video
|
= link_to 'Back', videos_path

app/views/videos/index.html.haml
%p#notice= notice
%h1 Videos
= render 'videos/videos'
%br/
= link_to 'New Video', new_video_path

app/views/videos/new.html.haml
%h1 New Video
= render 'form', video: @video
= link_to 'Back', videos_path

app/views/videos/show.html.haml
%p#notice= notice
%p
  %strong Title:
  = @video.title
%p
  %strong Url:
  = @video.url
%p
  %strong Stoptime:
  = @video.stoptime
- if @video.subtitle.present?
  %p
    = link_to @video.subtitle_upload_file.filename, rails_blob_path( @video.subtitle_upload_file, disposition: 'attachment')
= link_to 'Edit', edit_video_path(@video)
|
= link_to 'Back', videos_path